language: node_js
node_js:
  - "stable"
cache:
directories:
  - “node_modules”
before_install:
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coverage
env:
  global:
    - CODECLIMATE_REPO_TOKEN=c1325d32d45a10a411854b7f3c66f76c1ff752bd54a6c9636b8ae7e73a8bb75b